name: Checkout and Transfer Files

on: [push]

jobs:
  checkout-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Checkout another repository (Kainatos-packages)
        uses: actions/checkout@v3
        with:
          repository: KAINAT-OS/Kainatos-packages
          path: kainatos-packages

      - name: Copy the binary-settings/Builds/linux/K-settings folder to sources folder
        run: |
          cp -r binary-settings/Builds/linux/K-settings kainatos-packages/sources/

      - name: Commit and push changes
        working-directory: kainatos-packages
        run: |
          cd kainatos-packages
          sudo apt-get install git-lfs
          git lfs install
          git config --global user.email "kainatquaderee@users.noreply.github.com"
          git config --global user.name "kainatquaderee"
          git add .
          git commit -m 'Sync from K-SETTINGS'
          git push origin main
