name: Checkout and Transfer Files

on: [push]

jobs:
  checkout-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Checkout another repository (Kainatos-packages)
        uses: actions/checkout@v3
        with:
          repository: KAINAT-OS/Kainatos-packages
          path: kainatos-packages

      - name: Copy the binary-settings/Builds/linux/K-settings folder to sources folder
        run: |
          cp -r binary-settings/Builds/linux/K-settings kainatos-packages/sources/

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          cd kainatos-packages
          git add sources
          git commit -m "Update sources from K-SETTINGS"
          git push
